[project]
head-extra = '<script defer src="https://um.yawk.at/script.js" data-website-id="b5d4c506-bc83-46c4-a1d0-84defbe9736d"></script>'

[[model]]
file = "test.scad"
export-file-stem = {js = "shape + '-' + width + 'x' + depth + 'x' + height"}
# Track render events with selected model parameters
umami-track-render = ["shape", "width", "depth", "height"]
# Track export events with additional parameters
umami-track-export = ["shape", "width", "depth", "height", "rounding"]
