# generated by datamodel-codegen:
#   filename:  config-schema.json

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class Project(BaseModel):
    name: str | None = Field(None, description='Project name shown in the web export')
    uri: AnyUrl | None = Field(
        None, description='Project URI (link in the web interface)'
    )
    export_filename_prefix: str | None = Field(
        None, alias='export-filename-prefix', description='Prefix for downloaded files'
    )
    head_extra: str | None = Field(
        '', alias='head-extra', description='HTML injected at end of <head> tag'
    )


class FontSource(Enum):
    auto = 'auto'
    appimage = 'appimage'
    system = 'system'


class Openscad(BaseModel):
    version: str | None = Field(
        '2026.01.19',
        description='OpenSCAD version to download',
        pattern='^\\d{4}\\.\\d{2}\\.\\d{2}$',
    )
    sha256_appimage: str | None = Field(
        None,
        alias='sha256-appimage',
        description='SHA256 checksum of the OpenSCAD AppImage to download',
        pattern='^[0-9a-fA-F]{64}$',
    )
    sha256_wasm_web: str | None = Field(
        None,
        alias='sha256-wasm-web',
        description='SHA256 checksum of the OpenSCAD WASM web zip to download',
        pattern='^[0-9a-fA-F]{64}$',
    )
    font_source: FontSource | None = Field(
        'auto', alias='font-source', description='Font source selection'
    )
    enable_features: list[str] | None = Field(
        [],
        alias='enable-features',
        description='List of OpenSCAD experimental features to enable, passed as --enable=<feature> arguments.',
    )


class ExportFileStem(BaseModel):
    js: str | None = Field(None, description='JavaScript expression')
    fixed: str | None = Field(None, description='Fixed value')


class Presets(BaseModel):
    text: str | None = Field(
        'Presets', description='Text to display in the presets dropdown'
    )
    values: dict[str, list[float]] | None = None


class DisplayCondition(BaseModel):
    js: str | None = Field(None, description='JavaScript expression')
    fixed: bool | None = Field(True, description='Fixed value')


class ParamMetadata(BaseModel):
    require_present: bool | None = Field(
        True,
        alias='require-present',
        description="Require at least parameter of this name to exist. If a parameter of this name is not found, an error is thrown. This is on by default, but you can turn it off if you have wildcards that don't always match something.",
    )
    presets: Presets | None = Field(
        None, description='Named presets for this parameter'
    )
    display_condition: DisplayCondition | None = Field(
        default_factory=lambda: DisplayCondition.model_validate({}),
        alias='display-condition',
        description='Expression with a condition to display this parameter',
    )
    help_link: str | None = Field(
        None, alias='help-link', description='Help link for this parameter'
    )
    description_html: str | None = Field(
        None,
        alias='description-html',
        description='HTML description for this parameter. This replaces the description defined in the OpenSCAD file',
    )


class TabMetadata(BaseModel):
    collapsed: bool | None = Field(
        False, description='Whether this tab is collapsed by default'
    )
    help_link: str | None = Field(
        None, alias='help-link', description='Help link for this parameter'
    )
    control_boolean: str | None = Field(
        None,
        alias='control-boolean',
        description='parameter that is controlled by this tab',
    )
    description_html: str | None = Field(
        None, alias='description-html', description='HTML description for this tab.'
    )
    description_collapsible_html: str | None = Field(
        None,
        alias='description-collapsible-html',
        description='HTML description for this tab that is part of the collapsible section (or hidden by `control-boolean`).',
    )


class ModelConfig(BaseModel):
    template: list[str] | None = ['default']
    additional_params: list[str] | None = Field(
        [], alias='additional-params', description='Array of parameter JSON files'
    )
    additional_params_scad: list[str] | None = Field(
        [],
        alias='additional-params-scad',
        description='Array of OpenSCAD files to load additional params from',
    )
    description_extra_html: str | None = Field(
        None, alias='description-extra-html', description='Per-file HTML description'
    )
    export_file_stem: ExportFileStem | None = Field(
        None,
        alias='export-file-stem',
        description='Filename stem (without extension) for exported files',
    )
    param_metadata: dict[str, ParamMetadata] | None = Field(
        {},
        alias='param-metadata',
        description='Additional metadata for model parameters',
    )
    tab_metadata: dict[str, TabMetadata] | None = Field(
        {}, alias='tab-metadata', description='Additional metadata for model tabs'
    )
    umami_track_render: list[str] | None = Field(
        None,
        alias='umami-track-render',
        description='List of model parameter names to track when model is rendered. Set to null (default) to disable tracking, or [] to track with no parameters.',
    )
    umami_track_export: list[str] | None = Field(
        None,
        alias='umami-track-export',
        description='List of model parameter names to track when model is exported (STL download). Set to null (default) to disable tracking, or [] to track with no parameters.',
    )


class ModelItem(ModelConfig):
    file: str = Field(..., description='Path to SCAD file')
    index: bool | None = Field(
        None,
        description='Whether this model should be generated at index.html in the output. Can be set at most for one model. By default, for projects with a single model this is true for that model, and for projects with multiple models this is false for all models. Can be set at most once per project. If a project has no model defined as the index, a bare-bones index with a list of all models will be generated.',
    )


class WebOpenscadEditorConfiguration(BaseModel):
    project: Project | None = Field(
        None, description='Project metadata displayed in the web interface'
    )
    openscad: Openscad | None = Field(
        default_factory=lambda: Openscad.model_validate({}),
        description='OpenSCAD-specific configuration',
    )
    model_template: dict[str, ModelConfig] | None = Field({}, alias='model-template')
    model: list[ModelItem] = Field(
        ..., description='Input SCAD files to process', min_length=1
    )
